version: '3'
services:
  db:
    image: mariadb:10
    restart: always
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
volumes:
  mariadb-data:

networks: 
  default: 
    external: 
      name: database
