version: '3'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
volumes:
  mysql-data:

networks: 
  default: 
    external: 
      name: database
